### ISSUE TITLE
Using custom rpy2-arrow converter prevents conversion of dataframe from R back to Python

### ISSUE THREAD

**Issue by nkoep** [rpy2/rpy2-arrow#10]
Hi! I'm facing a problem while trying to convert a pandas dataframe from Python to R and back when using rpy2-arrow. I'm not quite sure what the real issue here is since rpy2's converters were always a bit of a mystery to me. It seems that adding an rpy2-arrow-based converter to my set of conversion rules as described [here](https://rpy2.github.io/rpy2-arrow/version/main/html/conversion.html#from-pandas-dataframe-to-and-arrow-table-visible-to-r) prevents the automatic conversion of an R data.frame back to Python. Here's a minimal working example demonstrating the issue. Note that due to limitations outside my control, I'm stuck with R 3.6, and hence arrow 4 in R, and thus rpy2-arrow 0.0.4 😅 

```python
import pandas as pd
import pyarrow
import rpy2.robjects as ro
import rpy2_arrow.pyarrow_rarrow as pyra
from rpy2.robjects import numpy2ri, pandas2ri
from rpy2.robjects.packages import importr


base = importr("base")

pandas_arrow_dataframe_converter = ro.conversion.Converter(
    "Convert pandas.DataFrame to R data.frame via arrow", template=pyra.converter
)


@pandas_arrow_dataframe_converter.py2rpy.register(pd.DataFrame)
def _(dataframe: pd.DataFrame):
    print("Using arrow converter")
    return base.as_data_frame(pyarrow.Table.from_pandas(dataframe))


CONVERTERS = (
    ro.default_converter
    + numpy2ri.converter
    + pandas2ri.converter
    + pandas_arrow_dataframe_converter
)


def main():
    code = """
    function(df) {
      library(dplyr)
      df %>% mutate(y = x * 2)
    }
    """
    rfunction = ro.r(code)

    df = pd.DataFrame({"x": range(10)})

    with CONVERTERS.context():
        output = rfunction(df)
    assert isinstance(output, pd.DataFrame)
    assert "y" in output.columns


if __name__ == "__main__":
    main()
```

This currently fails because `output` is returned as an instance of `rpy2.robjects.vectors.DataFrame` instead of `pd.DataFrame`. If I remove `pandas_arrow_dataframe_converter` from the definition of `CONVERTERS` everything works fine, but then I'm back to the inefficient rpy2 converter for pandas dataframes.

**Comment by lgautier** [comment]
`pandas_arrow_dataframe_converter` is using `pyra.converter` as a template. That template itself is based out of rpy2's default converter: https://github.com/rpy2/rpy2-arrow/blob/main/rpy2_arrow/arrow.py#L293
That converter will wrap R `data.frame` objects into `rpy2.robjects.vectors.DataFrame` R proxy objects.

In other words, you are overwriting the rules from `pandas2ri.converter` you want with rules in `pyra.converver`.

```python
pandas_arrow_dataframe_converter = ro.conversion.Converter(
    "Convert pandas.DataFrame to R data.frame via arrow", template=pandas2ri.converter
)


@pandas_arrow_dataframe_converter.py2rpy.register(pd.DataFrame)
def _(dataframe: pd.DataFrame):
    print("Using arrow converter")
    return base.as_data_frame(pyarrow.Table.from_pandas(dataframe))

# Add other conversion rules you want from here:
# https://github.com/rpy2/rpy2-arrow/blob/main/rpy2_arrow/arrow.py#L298

CONVERTERS = (
    ro.default_converter
    + numpy2ri.converter
    + pandas_arrow_dataframe_converter
)
```

**Comment by lgautier** [comment]
One more thing. There is an ambiguity about what a set of rules in converter shipping with `rpy2.robjects.numpy2ri`, `rpy2.robjects.pandas2ri`, or `rpy2_arrow.arrow`. The set of rules can a self-sufficient set of rules to be used as-is (the case for `rpy2_arrow.arrow`) , or a set of rules that is not self-sufficient and should be combined (for example with the set in rpy2's `default_converter` - this is the case for `pandas2ri`).

Providing both for all three would probably make sense.
